#!/usr/bin/env python3
import subprocess

subprocess.run([
    "/nix/store/w1hyhaxq3h9195bllxpbgq58f3jqzn91-ghidra-11.3.2/bin/ghidra-analyzeHeadless",
    "/home/hacker", "pwnproj",
    "-import", "/challenge/executable",
    "-overwrite"
    ], check=True)

subprocess.run(["/run/dojo/bin/ghidra", "/home/hacker/pwnproj.gpr"], check=True)
