#!/usr/bin/env python3
import subprocess

G = "/nix/store/cbqgq0nxkhbd8s8s2bpwi2vxg0rrnfsi-ghidra-11.4.2"

subprocess.run([f"{G}/bin/ghidra-analyzeHeadless", "/home/hacker", "pwnproj",
                "-import", "/challenge/executable", "-overwrite"],
               stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=True)

subprocess.Popen([f"{G}/bin/ghidra", "/home/hacker/pwnproj.gpr"])

print("Ghidra opened.")
