#!/usr/bin/env python3

import subprocess

GHIDRA_BIN = "/run/dojo/bin"
PROJECT_DIR = "/home/hacker"
PROJECT_NAME = "pwnproj"
PROJECT_FILE = f"{PROJECT_DIR}/{PROJECT_NAME}.gpr"
EXECUTABLE = "/challenge/executable"

subprocess.run([
    f"{GHIDRA_BIN}/ghidra-analyzeHeadless",
    PROJECT_DIR,
    PROJECT_NAME,
    "-import",
    EXECUTABLE,
    "-overwrite"
], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=True)

subprocess.Popen([
    f"{GHIDRA_BIN}/ghidra",
    PROJECT_FILE
])

print("Ghidra opened.")
